services:
  - type: web
    name: react-flask-app
    env: python
    buildCommand: |
      npm install
      npm run build
      pip install -r requirements.txt
    startCommand: gunicorn src.app:app
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: NODE_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.9.9
      - key: FLASK_APP
        value: src/app.py
      - key: FLASK_ENV
        value: production
    staticPublishPath: ./dist